[package]
name = "deskscope"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4.6", features = ["derive"] }
drm-fourcc = "2.2"
image = { version = "0.25", default-features = false, features = ["png"] }
libcamera = { version = "0.7", features = ["vendor_rpi"] }
serde = { version = "1.0", features = ["derive"] }
slint = "1.17"
toml = "1.1"
rppal = "0.22"

[build-dependencies]
slint-build = "1.17"
